version: 2
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    allow:
      # Allow both direct and indirect updates for all packages
      - dependency-type: "all"
    groups:
      github-actions:
        applies-to: version-updates
        patterns:
          - "*"
